backend:
  name: git-gateway
  branch: testing

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "category"
    label: "Category"
    folder: "src/pages/category"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date",format: 'YYYY-MM-DD'}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Parent", name: "parent", widget: "string"}
      - {label: "Featured Category", name: "featuredcategory", widget: "boolean", required: false}
      - {label: "Image", name: "image", widget: "image"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "User name", name: "username", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date",format: 'YYYY-MM-DD'}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Square Image", name: "squareimage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: object, fields: [{label: "category", name: "category", widget: list, fields: [{label: Title, name: title, widget: string}, {label: Slug, name: slug, widget: string}]}]}
      - {label: "Related Posts", name: "relatedpost", widget: object, fields: [{label: "blog", name: "blog", widget: list, fields: [{label: Title, name: title, widget: string}, {label: Slug, name: slug, widget: string}]}]}
      - {label: "Tags", name: "tags", widget: "list"}
      - { label: "Link", name: "link", widget: "string" }

  - name: "resilifyProgram"
    label: "Resilify Programs"
    folder: "src/pages/resilify/program"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "resilify-program"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Sequence", name: "sequence", widget: "number"}
      - {label: "Program Overview", name: "overview", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: object, fields: [{label: "category", name: "category", widget: list, fields: [{label: Title, name: title, widget: string}]}]}
      - {label: "Sessions", name: "sessions", widget: object, fields: [{label: "Session", name: "session", widget: list, fields: [{label: Title, name: title, widget: string},{label: Session Overview, name: overview, widget: text,required: false},{label: Activity Overview, name: activityOverview, widget: text,required: false}]}]}
      - {label: "Related Programs", name: "relatedpost", widget: object, fields: [{label: "program", name: "program", widget: list, fields: [{label: Title, name: title, widget: string}, {label: Slug, name: slug, widget: string}]}]}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "coachingExperts"
    label: "Coaching Experts"
    folder: "src/pages/coaching/experts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "coaching-experts"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Profile Image", name: "profileImage", widget: "string"}
      - {label: "Cover Image", name: "coverImage", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Title(Bio)", name: "titleBio", widget: "string"}
      - {label: "Sequence", name: "sequence", widget: "number"}
      - {label: "About", name: "about", widget: "markdown"}
      - {label: "Education", name: "qualifications", widget: list, fields: [{label: Certification, name: certification, widget: string},{label: School, name: school, widget: string},{label: Year, name: year, widget: string},{label: Image, name: image, widget: string,required: false}]}
      - {label: "Links", name: "links", widget: list, fields: [{label: Text, name: text, widget: string},{label: Link, name: link, widget: string}]}
      - {label: "Books", name: "books", widget: list, fields: [{label: Title, name: title, widget: string},{label: Short Description, name: shortDescription, widget: string},{label: Link, name: link, widget: string},{label: Image, name: image, widget: string,required: false}]}
      - {label: "Honors & Awards", name: "awards", widget: list, fields: [{label: Title, name: title, widget: string},{label: Given By, name: givenBy, widget: string},{label: Year, name: year, widget: string},{label: Image, name: image, widget: string,required: false}]}

  - name: "pressReleases"
    label: "Press Releases"
    folder: "src/pages/press"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "press-releases-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date",format: 'YYYY-MM-DD'}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "pressCoverage"
    label: "Press Coverage"
    folder: "src/pages/press/coverage"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "press-coverage-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date",format: 'YYYY-MM-DD'}
      - {label: "Image", name: "image", widget: "image",required: false}
      - {label: "Link", name: "link", widget: "string",required: false}
